### ISSUE TITLE
Webroot SecureAnywhere recognized it as a virus

### ISSUE THREAD

**Issue by zeljkoavramovic** [iklevente/ChromiumForWindows#1]
During installation, update.exe and update.dll were recognized as viruses and quarantined.

**Comment by iklevente** [comment]
Yes. Unfortunately McAfee does this too. Sometimes it recognise it as a virus and sometimes not. My only solution currently is to make the project compatible with Hibbiki's Chromium installer and if It will work, I really don't want to touch it again. (Only some fixes if it gets wrong for some reason.) If I'm done I will upload it to virustotal.com and I will report it to every antivirus service which sees it false positive.

You can try downloading the source code for each release at the releases page, and you can build it for yourself, if that helps.

**Comment by eggplanting** [comment]
Doesn't happen for me with Kaspersky. After checking the latest build (1.5) with Virustotal, the result seems fine to me. The 3 engines still recognizing it as malicious are not trustworthy in my eyes.

![virustotalcfw](https://user-images.githubusercontent.com/57031979/82147407-baad9d80-984f-11ea-96b2-93d419e49ac6.png)

**Comment by daze-2121** [comment]
I want to trust and use this project, but the author literally writes code for stealing Discord tokens. I don't know man. Something just seems off.

**Comment by iklevente** [comment]
It is literrally an open source project. You can go trough the source code to see if you can find anything spicy.

I am not intended to hack or steal anything from anyone's computer. I made Discord token grabbers because it was a great way to learn C# REGEX functions. And it actually ended up as a useful software. You can see that I was working with regex a lot: [RegexValidator](https://github.com/iklevente/RegexValidator), [ChromiumForWindows GetFileVersion.cs](https://github.com/iklevente/ChromiumForWindows/blob/master/ChromiumForWindows-ungoogled/GetFileVersion.cs), and of course the token grabbers. Regex is a great way to get the required information from long and complicated text documents.

You can also build ChromiumForWindows for yourself, if you clone the repository:
- Open .sln file
- Set the project to release
- Press Ctrl + Shift + B to compile
- Copy the files from the bin/releases/ folder (bin folder is located at .sln file after compiling is done
- Paste the files at %localappdata%/Chromium/ and start the .exe

It will automatically install the latest Chromium and put an Icon on the desktop.

**Comment by iklevente** [comment]
The false detection might be because I am using InnoSetup to create Setup.exe-s for the software.
InnoSetup can create an installer for your software, but InnoSetup's own Installer already came up as a false alarm on Virustotal: https://www.virustotal.com/gui/file/ae6823b523df87e9441789e51845434e4e0e70aac0b88afe80f94f20f4b98acb/detection
 
Insteresting because this Installer creator is well known and used by many people, even GitHub recognises the .iss files as "Inno Setup Install Script" files.

This is the Installer extrated ChromiumLauncher.exe file: https://www.virustotal.com/gui/file/64ca4e7e4b819a4dd61168c079f3f91d6c43cd1974aae5f4ad09b365723ef7df/detection
As you can see 0/70 detection rate so I don't understand why does it detect it after compressing it into an installer.

**Good news:** I am working on a custom Material Design themed open source installer for this project. It is being written from the ground up completely by me and hopefully no false detections will appear when it's finished.

**Comment by iklevente** [comment]
The new ChromiumForWindows 2.0 provides everything to build it up from source code. Even the InnoSetup install script.
Build it yourself and you will get the same [results](https://www.virustotal.com/gui/file/afb3a794dada5b76bb80fe9213a87fca633eb6dc4b0d85f8c31ae35356f5d6f9/detection).
Currently only 2 antivirus shows false positive. (2/69)
I can't really do much about it, so I'm closing this issue. Building it by yourself is always an option if you don't trust in my releases.

**Comment by iklevente** [comment]
Kaspersky Lab was kind enough to analyse the software and it is now even proven by them, that this is **NOT** a malicious software.

![](https://i.imgur.com/gaLF4bP.png)
![](https://i.imgur.com/svfru2D.png)

Therefore this issue won't be opened again. Use a trustworthy antivirus or report the false positive to your antivirus developer.
