### ISSUE TITLE
[Feature request] Build choices - Ungoogled Chromium / Hibbiki no-sync

### ISSUE THREAD

**Issue by eggplanting** [iklevente/ChromiumForWindows#2]
Hi, thanks a lot for this nice updater.

I'd appreciate if we could choose between following builds when running the Updater first time:
- Ungoogled Chromium: https://github.com/macchrome/winchrome/releases
- Hibbiki with Google Sync
- Hibbiki without Google Sync

It would be great if Ungoogled Chromium could be added:
https://github.com/macchrome/winchrome/releases

**Comment by iklevente** [comment]
Good idea. I will be working on that too. 🙂

**Comment by eggplanting** [comment]
Wow, thanks for the fast response. I'm eagerly waiting for a new release and will support this project. Awesome work!

Next suggestion incoming. :)

**Comment by tooomm** [comment]
Ungoogled would be awesome, indeed.

**Comment by iklevente** [comment]
Ungoogled version is ready. It's in the latest [Release](https://github.com/iklevente/ChromiumForWindows/releases/)
It does not support "Make as default" option, since Marmaduke does not include that in his builds. Trying to find a fix for it.

I also started working on a "ChromiumForWindows Settings" interface, where you will be able to set your preferred Chromium version, add windows startup flag/options and enable/disable portable option.

**Comment by iklevente** [comment]
Ungoogled Chromium now supports the default browser setting! The old updater broke this function, since the new Ungoogled release from Marmaduke can not communicate with the updater.
The updater is patched in the latest (1.5.4) release so if you have problems with setting ungoogled Chromium as the default browser, please do the tasks mentioned in the release note to fix it!

Sorry for the inconvenience and thank you for your feedback!

I'll continue the Settings interface and dedicated installer project which should be the last big update. After that the software should automatically update itself.

**Comment by iklevente** [comment]
The new ChromiumForWindows 2.0 makes it much easier to switch between builds. Check README.md gifs.
Hibbiki nosync is still missing but I will include them in a future release with RobRich's builds.

**Comment by iklevente** [comment]
- Hibbiki nosync added in CFW 2.1 ✅

**The remaining builds that are not included:**
- RobRich (features compiler optimizations)
- RAW (from the official Chromium Authors) (updated extremely frequently, very unstable)

Unfortunately is no API like GitHub's .../releases/latest url that would redirect the updater to the latest binary file to download it so I can't really do anything about it right now. I will try my best to solve it somehow, but I can't promise anything.
