### ISSUE TITLE
[Improvement] Resolution of Desktop Icon

### ISSUE THREAD

**Issue by eggplanting** [iklevente/ChromiumForWindows#4]
Hi,

after installing your updater, an icon is placed to launch Chromium. The resolution of the icon doesn't look good on my system. You can probably replace it with the official Chromium icon, which has a better resolution.

Icon of ChromiumForWindows Launcher:
![Icon-Resolution_ChromiumForWindows](https://user-images.githubusercontent.com/57031979/82147285-feec6e00-984e-11ea-8cf4-28a9b6671067.png)

Icon of official Chromium:
![ChromiumIcon](https://user-images.githubusercontent.com/57031979/82147345-60acd800-984f-11ea-8cff-9a8f477e6d98.png)

**Comment by iklevente** [comment]
I've tried. I found the highest resolution that I could get. If I open the image in my photo viewer, it looks fine, but Visual Studio makes it pixelated for some reason. I will try to find someting for that too.

**Comment by eggplanting** [comment]
I see. :)

The workaround on my system: I replaced the icon of the shortcut with the official Chromium icon.

**Comment by iklevente** [comment]
Cool. The problem is that it will replace the workaround shortcut after a new version is installed, because Hibbiki's Chromium installer replaces the Updater's shortcut to the original chrome.exe's shortcut's location. That's why I made the FixShortcut.cs class to replace it (again) with my Launcher's shortcut. A bit complicated to get it working with Hibbiki's installer, but you can always contribute or change the code to your needs.

Also, your workaround might got me an idea to fix the pixelated icon, so thanks a lot! 😁

**Comment by iklevente** [comment]
Alright, your workaround was implemented into the code. The icon is not pixelated now. The improvement will be avalible in the next Release. 😀
