### ISSUE TITLE
Updater breaks default app due to outdated registry entry

### ISSUE THREAD

**Issue by timotejroiko** [iklevente/ChromiumForWindows#8]
Hello, when the updater installs a new version (in my case ungoogled chromium), it deletes the chromium folder and creates a new one with a different version number, but the following registry key is not updated causing the "default app" functionality in many third-party software to break (ie opening links in mozilla thunderbird).

`\HKEY_CLASSES_ROOT\Chromium<random characters>\shell\open\command`

This registry key should be updated with the new chromium folder on every update. Alternatively keep the chromium folder or a symlink to it always named the same.

The Application and DefaultIcon entries in `\HKEY_CLASSES_ROOT\Chromium<random characters>` should also have their paths updated to fix the Chromium icon disappearing

**Comment by iklevente** [comment]
Oh my gosh, thank you for your help regarding how to solve this issue! I will try fix that as soon as I can!

Contributions are also always welcome! 😁

**Comment by iklevente** [comment]
Hi! I started working on a fix for the Registry.

I realised that ungoogled chromium now generates itself a registry values so now you can set it as a default browser to open files.
The probem is that every time a new version is released, the updater downloads and extracts it and leaves the folder name as it was, including the current version in it.

My first idea was to delete the previous registry values so Chromium will generate a new one for itself, however it seems too complicated, so I will probably change the code so that the updater renames the chromium folder to the same every time.

I will edit the current release (1.5.3), since it's not a major change and the next release will be coming out with the new installer. Written by me, not a third party installer. Open source as always. 😊

I will tell you when I updated the current release.

**Comment by iklevente** [comment]
Hotfix dropped in the latest release. Please do the required steps, that are mentioned in the release note to fix the registry bug!

Sorry for the inconvenience and thank you for your feedback!

**Comment by timotejroiko** [comment]
Thanks :)
